### ISSUE TITLE
not compiling (Windows 7, Arduino 1.6.4

### ISSUE THREAD

**Issue by jkervinen** [enveloop/miniMO#1]
Arduino: 1.6.4 (Windows 7), Board: "ATtiny25/45/85, ATtiny85, Internal 8 MHz"

C:\Users\jukka\AppData\Local\Temp\build2721530541697366340.tmp/core.a(wiring.c.o): In function `__vector_5':
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/wiring.c:49: multiple definition of `__vector_5'
LunaMod.cpp.o:C:\Program Files (x86)\Arduino/LunaMod.ino:111: first defined here
collect2.exe: error: ld returned 1 exit status
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by enveloop** [comment]
I think the issue is related to your arduino IDE version, which is 1.6.4. I'm currently supporting IDE 1.5.7, as explained here:
[http://minimosynth.com/how_to_program_minimo/](http://minimosynth.com/how_to_program_minimo/)
Please try compiling with 1.5.7, and let me know if you still have issues.

**Comment by jkervinen** [comment]
OK, thanks of quick reply ! I uninstalled 1.6.4 and installed 1.5.7 back, had already tried with it, compiled without problems, but wasn't able to upload to Minimo. Not sure if 1.6.4 left some extra USB driver, as now it worked, both compiling and uploading.

**Comment by enveloop** [comment]
Nice to know that you got it to work! :D
