### ISSUE TITLE
Adding a license file

### ISSUE THREAD

**Issue by leobrowning92** [enveloop/miniMO#2]
Not sure what you want to use as a license, but the default GNU,MIT or Apache licenses that they suggest on github are pretty good. 

I think its an easy thing to make sure that you vision of open source is upheld, and that people credit you for your work (if thats what you want)

cant wait to get started on building some of these! what a great idea concept and clean execution :)

**Comment by enveloop** [comment]
Thanks! :)

I do use a license, CC BY 4.0; all the programs include it at the very beginning, and there are license.txt files in the parts and schematic folders.

**Comment by leobrowning92** [comment]
sorry for the oversight, i just have gotten so used to seeing the license file right by README that I didn't check further down!

Cheers.

**Comment by enveloop** [comment]
No problem, and thanks again!
